version: "3.7"
services:
  db:
    image: 'postgres:13-alpine'
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
  rails-example:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && bin/webpack-dev-server"
    volumes:
      - .:/educatit
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_NAME: app_db
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      RAILS_SERVE_STATIC_FILES: 'true'
  redis:
    image: redis:5.0-alpine
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
volumes:
  redis:
