version: "3.7"

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  environment: &env
    NODE_ENV: development
    RAILS_ENV: ${RAILS_ENV:-development}

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/educatit
  environment: &backend_environment
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
    DB_PORT: 5432
    DB_NAME: app_db
    DB_HOST: db
    RAILS_MAX_THREADS: 5
    RAILS_SERVE_STATIC_FILES: 'true'
    CHROME_URL: http://chrome:3333
  depends_on: &backend_depends_on
    db:
      condition: service_healthy
    redis:
      condition: service_healthy
services:
  db:
    image: 'postgres:13-alpine'
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  rails:
    <<: *backend
    command: /bin/ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && bin/webpack-dev-server"
    ports:
      - "3000:3000"
      - "3035:3035"

  # Separate definition for system tests to add Chrome as a dependency
  rspec_system:
    <<: *backend
    command: /bin/ash -c "rspec"
    ports:
      - '3000:3000'
      - '50051'
    environment:
      <<: *backend_environment
      RAILS_ENV: test
    depends_on:
      <<: *backend_depends_on
      chrome:
        condition: service_started
  redis:
    image: redis:5.0-alpine
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
  chrome:
    image: browserless/chrome:1.31-chrome-stable
    ports:
      - '3333:3333'
    environment:
      PORT: 3333
      # Set connection timeout for debugging
      # https://docs.browserless.io/docs/docker.html#connection-timeout
      CONNECTION_TIMEOUT: 600000

volumes:
  redis:
