default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: educatit_development

test:
  <<: *default
  database: educatit_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

